/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_pietu1998_wordbasehacker_solver_NativeSolver */

#ifndef _Included_net_pietu1998_wordbasehacker_solver_NativeSolver
#define _Included_net_pietu1998_wordbasehacker_solver_NativeSolver
#ifdef __cplusplus
extern "C" {
#endif
#undef net_pietu1998_wordbasehacker_solver_NativeSolver_UNKNOWN
#define net_pietu1998_wordbasehacker_solver_NativeSolver_UNKNOWN 0L
#undef net_pietu1998_wordbasehacker_solver_NativeSolver_EMPTY
#define net_pietu1998_wordbasehacker_solver_NativeSolver_EMPTY 1L
#undef net_pietu1998_wordbasehacker_solver_NativeSolver_ORANGE
#define net_pietu1998_wordbasehacker_solver_NativeSolver_ORANGE 2L
#undef net_pietu1998_wordbasehacker_solver_NativeSolver_BLUE
#define net_pietu1998_wordbasehacker_solver_NativeSolver_BLUE 3L
#undef net_pietu1998_wordbasehacker_solver_NativeSolver_MINE
#define net_pietu1998_wordbasehacker_solver_NativeSolver_MINE 4L
#undef net_pietu1998_wordbasehacker_solver_NativeSolver_SUPER_MINE
#define net_pietu1998_wordbasehacker_solver_NativeSolver_SUPER_MINE 5L
/*
 * Class:     net_pietu1998_wordbasehacker_solver_NativeSolver
 * Method:    setScoring0
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_net_pietu1998_wordbasehacker_solver_NativeSolver_setScoring0
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_pietu1998_wordbasehacker_solver_NativeSolver
 * Method:    setParams0
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_net_pietu1998_wordbasehacker_solver_NativeSolver_setParams0
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     net_pietu1998_wordbasehacker_solver_NativeSolver
 * Method:    initBoard0
 * Signature: ([C)Z
 */
JNIEXPORT jboolean JNICALL Java_net_pietu1998_wordbasehacker_solver_NativeSolver_initBoard0
  (JNIEnv *, jclass, jcharArray);

/*
 * Class:     net_pietu1998_wordbasehacker_solver_NativeSolver
 * Method:    addWord0
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_pietu1998_wordbasehacker_solver_NativeSolver_addWord0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_pietu1998_wordbasehacker_solver_NativeSolver
 * Method:    removeWord0
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_pietu1998_wordbasehacker_solver_NativeSolver_removeWord0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_pietu1998_wordbasehacker_solver_NativeSolver
 * Method:    solve0
 * Signature: (ZZ[B[B[C[I)I
 */
JNIEXPORT jint JNICALL Java_net_pietu1998_wordbasehacker_solver_NativeSolver_solve0
  (JNIEnv *, jclass, jboolean, jboolean, jbyteArray, jbyteArray, jcharArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_pietu1998_wordbasehacker_solver_NativeSolver_Params */

#ifndef _Included_net_pietu1998_wordbasehacker_solver_NativeSolver_Params
#define _Included_net_pietu1998_wordbasehacker_solver_NativeSolver_Params
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
